[colors.primary]
background = "#030303"
foreground = "#ffffff"
dim_foreground = "#7f849c"
bright_foreground = "#111111"

[colors.cursor]
text = "#edebb2"
cursor = "#edebb2"

[colors.vi_mode_cursor]
text = "#edebb2"
cursor = "#edebb2"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

[colors.normal]
black = '0x282828'
red = '0xcc241d'
green = '0x98971a'
yellow = '0xd79921'
blue = '0x458588'
magenta = '0xb16286'
cyan = '0x689d6a'
white = '0xa89984'

[colors.bright]
black = '0x928374'
red = '0xfb4934'
green = '0xb8bb26'
yellow = '0xfabd2f'
blue = '0x83a598'
magenta = '0xd3869b'
cyan = '0x8ec07c'
white = '0xebdbb2'

[[colors.indexed_colors]]
index = 16
color = "#10101b"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"

[window]
decorations = "None"
startup_mode = "Maximized"
opacity = 1

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "VictorMono" }
size = 13
 
[env]
term = "xterm-256color"

[mouse]
hide_when_typing = true

[terminal]
shell = "zsh"
